name: quick_tracker
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  expense_repository:
    path: packages/expense_repository
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.69.0
  intl: ^0.20.2
  flex_color_picker: ^3.6.0
  firebase_core: ^3.12.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/img/
    - packages